# Use the MySQL official image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD="password"
ENV MYSQL_DATABASE="mydb"
ENV MYSQL_USER="user"
ENV MYSQL_PASSWORD="password"

# Expose port 3306 (default MySQL port)
EXPOSE 3306
